name: dartmission
description: Our Flutter puzzle for the FlutterPuzzleHack event on 2022
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gen_runner: ^4.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_svg: ^1.0.3
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^2.3.1
  intl: ^0.17.0
  rive: ^0.8.1

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/launcher.png"
  adaptive_icon_background: "#190946"
  adaptive_icon_foreground: "assets/images/png/launcher.png"

flutter_native_splash:
  background_image: "assets/images/png/splash_movil.png"

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true
  output: lib/gen/

flutter:
  assets:
    - assets/images/svg/
    - assets/images/jpg/
    - assets/images/png/
    - assets/rive/
  generate: true
  uses-material-design: true