name: dartmission

on: [pull_request, push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - name: get dependencies
        run: flutter packages get
      - name: valid format
        run: flutter format --set-exit-if-changed lib
      - name: analyze
        run: flutter analyze lib